CITATION.md, README.md
This pull request adds links to the medRxiv preprint and youtube tutorial into the readme
README.md
=> add video and manuscript link to readme

src/stepcount/hmm_utils.py, src/stepcount/sslmodel.py
Gracefully handle no data/empty array errors
=> Gracefully handle no data/empty array errors

README.md, rf-feature-list.md
Add documentation for ML model type.
Add documentation with the list of features for the random forest model
=> Feature add documentation

setup.py
Fixes #49 with higher actipy version.
=> Fix: update setup.py to require actipy>=3.0.5 to fix #49

src/stepcount/stepcount.py
Closes https://github.com/OxWearables/stepcount/issues/59
=> fix(read): handle filenames containing dots, confusing extension

src/stepcount/stepcount.py
Fixes NaT freq issue with extremely small files (one window)
=> fix NaT freq issue when recording is extremely small

src/stepcount/stepcount.py
StepsQ1At, StepsQ2At, StepsQ3At -> Steps25thAt, Steps50thAt, Steps75thAt
New: Steps5thAt, Steps95thAt
=> feat: steps 5th & 95th ptiles at; refactor field names

data-dictionary.md, src/stepcount/stepcount.py
- Drop StepsNthDayMedAt
- Rename StepsNthDayAvgAt -> StepsNthAt
=> chore: deprecate median ptiles at; shorten field names

src/stepcount/stepcount.py
Previous adjustment by mean imputation not adequate for max and 95th ptiles.
New method is as follows:
1. Calculate Peak-1, Peak-30 and 95th cadence for each day as before, except this time only if there are at least 30-min of walking in the day, otherwise set to NA.
2. Adjustments based on the average by median (it was mean before) across days.
=> Fix cadence adjustment

src/stepcount/stepcount.py
For example, if `--exclude-wear-below 10h`, days with <10h of wear time will be excluded in the analysis.
=> feat: add `--exclude-wear-below` option to exlude days with insufficient wear time

src/stepcount/models.py
Instead of reloading at every predict(), check whether it is already loaded.
=> refactor: improve how ssl model is loaded

src/stepcount/stepcount.py
Implemented mainly so we don't re-impute user-excluded days.
=> feat(impute_missing): option to skip full missing days in imputation

src/stepcount/stepcount.py
Related: b85d15fc6d5278c2a30760d5acda728660a97a90
=> fix: use median in impute_days for cadence only

src/stepcount/stepcount.py
- 'time' -> 'Time' or 'Date' for daily files
- add 'Filename' column for reference
=> refactor: add 'Filename' column; rename 'time' column

src/stepcount/stepcount.py, src/stepcount/utils/collate_outputs.py
Closes https://github.com/OxWearables/stepcount/issues/116
=> feat: include package version and input args used to run script

src/stepcount/models.py, src/stepcount/stepcount.py
Calculate hour-of-day averages, for example:
```
"Walking(mins)_Hour13": 4.666666666666667,
"Walking(mins)_Hour14": 3.6666666666666665,
"Walking(mins)_Hour15": 0.0,
...
```
=> feat: hour-of-day averages

src/stepcount/stepcount.py
For example:
```
"ENMO(mg)": 26.360278485554524,
"ENMO(mg)_Weekend": NaN,
"ENMO(mg)_Weekday": 26.360278485554524,
...
"ENMO(mg)_Hour22": NaN,
"ENMO(mg)_Hour23": NaN,
"ENMO(mg)_Weekend_Hour00": NaN,
"ENMO(mg)_Weekend_Hour01": NaN,
...
```
=> feat: weekend and weekday stats

src/stepcount/stepcount.py
A bug can occur when the nearest-neighbor indexing inserts data into the original na dates
=> fix(impute_missing): record NA dates before reindexing, not after

src/stepcount/cli_utils/collate_outputs.py
- Add missing `Filename` columns to output bouts data
- `collate_outputs`: overwrite (not append) existing files
- `collate_outputs`: collate bouts files
=> fix: overwrite existing collated files (not append); fix and collate bouts files

src/stepcount/stepcount.py
**Unified walking threshold**: Replaced separate arguments for `peak1`, `peak30`, and `p95` minimum walking time thresholds with a single `--min-walk-per-day` argument in the `main` function and throughout the cadence calculation logic. This change reduces redundancy and simplifies the configuration. [[1]](diffhunk://#diff-f5180fc712e0571c60c5373246163b12fa661c90e9ec17f1c1ec2d7620c670d6L63-R74) [[2]](diffhunk://#diff-f5180fc712e0571c60c5373246163b12fa661c90e9ec17f1c1ec2d7620c670d6L287-R290) [[3]](diffhunk://#diff-f5180fc712e0571c60c5373246163b12fa661c90e9ec17f1c1ec2d7620c670d6L307-R308)
=> refactor: simplify min-walk-per-day argument

GLOSSARY.md, src/stepcount/stepcount.py
This reverts commit f7319aeaefef38434db43fb3b4951f62c7617a55.
=> Revert "refactor: rename 'peak' to 'top' for improved clarity"

src/stepcount/stepcount.py
- Remove W parameter from summarize_bouts function signature
- Add steptol parameter with default value of 3 to match other functions
- Re-derive W internally using Y >= steptol logic, same as summarize_steps/cadence
- Update function call to pass steptol instead of W parameter
- Update docstring to reflect new parameter structure
=> fix: make summarize_bouts signature consistent with other summarize functions
